In [6]:
import pandas as pd

df = pd.read_csv("tuning_raw.csv", sep=";")
df.head()

,scenario,N,Tn,rsus,seed,best_objective,best_c0_s,best_c1_s,best_c2_s
0,cell,"(2.0, 1.0, 3.0)","(90.0, 120.0, 60.0)",422,1,-0.740819,0.740891,0.799917,0.740819
1,cell,"(2.0, 1.0, 3.0)","(90.0, 120.0, 60.0)",422,2,-0.736319,0.736954,0.793008,0.736319
2,cell,"(2.0, 1.0, 3.0)","(90.0, 120.0, 60.0)",422,3,-0.736771,0.736776,0.794202,0.736771
3,cell,"(2.0, 1.0, 3.0)","(90.0, 120.0, 60.0)",422,4,-0.735688,0.735690,0.770722,0.735688
4,cell,"(2.0, 1.0, 3.0)","(90.0, 120.0, 60.0)",422,5,-0.733874,0.738519,0.782926,0.733874

In [7]:
df = df[df["rsus"] == 422]
df[["scenario", "best_objective", "best_c0_s", "best_c1_s", "best_c2_s"]].groupby("scenario").mean()

          best_objective  best_c0_s  best_c1_s  best_c2_s
scenario
cell           -0.734962   0.736260   0.792973   0.735317
graph          -0.767159   0.789434   0.767259   0.767332